// apps/core-service/src/config.ts
export const config = {
  PORT: Number(process.env.PORT) || 8080,
  LOG_LEVEL: process.env.LOG_LEVEL || 'info',
  DATABASE_URL: process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/decoration_bidding',
  REDIS_URL: process.env.REDIS_URL || 'redis://localhost:6379',
  STORAGE_DRIVER: process.env.STORAGE_DRIVER || 'local',
  UPLOAD_DIR: process.env.UPLOAD_DIR || './uploads',
  BASE_URL: process.env.BASE_URL || 'http://localhost:8080',
  BIM_SERVICE_URL: process.env.BIM_SERVICE_URL || 'http://localhost:3008',
  AI_AGENT_SERVICE_URL: process.env.AI_AGENT_SERVICE_URL || 'http://localhost:3005',
  CORS_ORIGIN: process.env.CORS_ORIGIN || '*',
  RS256_PRIVATE_KEY: process.env.RS256_PRIVATE_KEY || '',
  RS256_PUBLIC_KEY: process.env.RS256_PUBLIC_KEY || '',
  ACCESS_TOKEN_TTL: 15 * 60,
  REFRESH_TOKEN_TTL: 7 * 24 * 3600,
  SMTP_HOST: process.env.SMTP_HOST || 'smtp.mailtrap.io',
  SMTP_PORT: Number(process.env.SMTP_PORT) || 587,
  SMTP_USER: process.env.SMTP_USER || '',
  SMTP_PASS: process.env.SMTP_PASS || '',
  SMTP_FROM: process.env.SMTP_FROM || 'noreply@decoration-bidding.com',
  LOGIN_MAX_FAILURES: process.env.NODE_ENV === 'production' ? 5 : 9999,
  LOGIN_LOCK_TTL: 30 * 60,
} as const
